<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find dviratis_robotas)/urdf/colors.xacro" />
	<xacro:include filename="$(find dviratis_robotas)/urdf/param.xacro" />

	<xacro:macro name="box_inertia" params="m x y z">
		<inertia ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0" iyy="${m*(x*x+z*z)/12}" iyz = "0" izz="${m*(x*x+z*z)/12}" />
	</xacro:macro>

	<xacro:macro name="cylinder_inertia" params="m r h">
		<inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
	</xacro:macro>

	<macro name="wheel_link" params="name">
		<link name="${name}">
			<inertial>
				<mass value="${wheel_m}"/>
				<origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
				<cylinder_inertia m="${wheel_m}" r="${wheel_r}" h="${wheel_w}"/>
			</inertial>
			<collision name="${name}_collision">
				<origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
				<geometry>
					<cylinder length="${wheel_m}" radius="${wheel_r}"/>
				</geometry>
			</collision>
			<visual name="${name}_visual">
				<origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
				<geometry>
					<cylinder length="${wheel_m}" radius="${wheel_r}"/>
				</geometry>
			</visual>
		</link>
	</macro>

	<macro name="battery_and_rpy" params="name x y z">
		<link name="${name}_rpy">
			<visual>
				<geometry>
					<box size="${rpy_x} ${rpy_y} ${rpy_z}" />
				</geometry>
				<material name="red"/>
			</visual>
		</link>

		<link name="${name}_batt">
			<visual>
				<geometry>
					<box size="${batt_x} ${batt_y} ${batt_z}" />
				</geometry>
				<material name="yellow"/>
			</visual>
		</link>

		<joint name="batt_to_rpy" type="fixed">
			<parent link="${name}_batt"/>
			<child link="${name}_rpy"/>
			<origin xyz="0 ${(rpy_y+batt_y)/2} ${(-batt_z+rpy_z)/2}"/>
		</joint>

		<joint name="base_to_batt" type="fixed">
			<parent link="chassis_link"/>
			<child link="${name}_batt"/>
			<origin xyz="${x} ${y+batt_y/2-(batt_y+rpy_y)/2} ${z}"/>
		</joint>
	</macro>

</robot>