<?xml version="1.0"?>
<robot name="dr_robotas"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find dviratis_robotas)/urdf/colors.xacro" />
  <xacro:include filename="$(find dviratis_robotas)/urdf/macros.xacro" />
  <xacro:include filename="$(find dviratis_robotas)/urdf/param.xacro" />

  <!-- links -->
  <link name="base_link">
    <visual name="base_link_visual">
      <geometry>
        <box size="${total_length} ${total_width} ${base_z}" />
      </geometry>
      <origin xyz="${(total_length-pcb_x)/2+pcb_x_offset-base_padding} 0 0"/>
      <material name="orange"/>
    </visual>
    <collision name="base_link_collision">
      <geometry>
        <box size="${total_length} ${total_width} ${base_z}" />
      </geometry>
      <origin xyz="${(total_length-pcb_x)/2+pcb_x_offset-base_padding} 0 0"/>
    </collision>
  </link>

  <link name="pcb">
    <visual>
      <geometry>
        <box size="${pcb_x} ${pcb_y} ${pcb_z}" />
      </geometry>
      <material name="green"/>
    </visual>
  </link>

  <xacro:battery_and_rpy name="link_right_wheel" x="${gap_pcb_bat+(batt_x+pcb_x)/2+pcb_x_offset}" y="${0}" z="${(batt_z+base_z)/2}"/>
  <xacro:wheel_link name="right_wheel_link"/>
  <xacro:wheel_link name="left_wheel_link"/>


  <link name="caster_front_link">
    <visual name='caster_visual'>
      <geometry>
        <sphere radius="${caster_wheel_r}"/>
      </geometry>
    </visual>
    <collision name='caster_collision'>
      <geometry>
        <sphere radius="${caster_wheel_r}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
  </link>

  <!-- joints -->
  <joint name="base_to_caster" type="fixed">
    <parent link="base_link"/>
    <child link="caster_front_link"/>
    <origin xyz="${(total_length-pcb_x)+pcb_x_offset-base_padding} 0 -${caster_wheel_r+pcb_z/2}"/>
  </joint>

  <joint name="base_to_pcb" type="fixed">
    <parent link="base_link"/>
    <child link="pcb"/>
    <origin xyz="${pcb_x_offset} 0 ${pcb_z/2+base_z/2}"/>
  </joint>

  <joint name="base_to_rwheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-(wheel_w+total_width)/2} -${motor_r+pcb_z/2}"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint name="base_to_lwheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${(wheel_w+total_width)/2} -${motor_r+pcb_z/2}"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

</robot>