<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_r" value="0.034" />
    <xacro:property name="wheel_w" value="0.026" />
    <xacro:property name="wheel_m" value="3.0" />

    <xacro:property name="rpy_x" value="0.1" />
    <xacro:property name="rpy_y" value="0.07" />
    <xacro:property name="rpy_z" value="0.035" />

    <xacro:property name="batt_x" value="0.12" />
    <xacro:property name="batt_y" value="0.03" />
    <xacro:property name="batt_z" value="0.04" />

    <xacro:property name="base_z" value="0.005" />

    <xacro:property name="pcb_x" value="0.05" />
    <xacro:property name="pcb_x_offset" value="-0.025" />
    <xacro:property name="pcb_y" value="0.05" />
    <xacro:property name="pcb_z" value="0.005" />

    <xacro:property name="gap_pcb_bat" value="0.02" />
    <xacro:property name="base_padding" value="0.01" />

    <xacro:property name="motor_r" value="0.00775" />

    <xacro:property name="caster_wheel_r" value="${(motor_r+wheel_r)/2}" />

    <xacro:property name="total_length" value="${batt_x+pcb_x+gap_pcb_bat+base_padding*2}" />
    <xacro:property name="total_width" value="${batt_y+rpy_y+base_padding*2}" />


</robot>